### ISSUE TITLE
BackgroundReplacementApp not working anymore (4.0.0-beta.3)

### ISSUE THREAD

**Issue by Titoine** [fritzlabs/fritz-android-tutorials#35]
Since updating to the last version, the BackgroundReplacementApp is broke.
Here a screen when I try to do the segmentation.

![image](https://user-images.githubusercontent.com/3514286/64937147-6c2ba780-d859-11e9-9281-e9707cef8ec8.png)

It was working correctly on the previous sdk (it was a v3.x.x I think.).
I have a Galaxy S8 with Android 9.

**Comment by hsiaoer** [comment]
Hi @Titoine - I wasn't able to replicate your issue. Can you walk me through the steps you're taking to get that result? Are there any code changes you've made to the app?

**Comment by Titoine** [comment]
No, I didn't make any change, It's a fresh install.
I just launch the app from Android Studio and take a picture.

**Comment by hsiaoer** [comment]
Do you mind if you sending me an email eric@fritz.ai or joining our slack group https://heartbeat.fritz.ai/join-the-conversation-heartbeats-new-slack-community-620000da5819? You can DM me at "Eric (Fritz)". Would like to see what's causing that.
